import { useStore } from '../state/useStore';
import { CheckCircle, Download, RotateCcw } from 'lucide-react';

interface FinalProps {
  onRestart: () => void;
}

export const Final = ({ onRestart }: FinalProps) => {
  const intent = useStore(state => state.intent);
  const draft = useStore(state => state.draft);
  const iteration = useStore(state => state.iteration);
  const previousDrafts = useStore(state => state.previousDrafts);

  const handleDownload = () => {
    if (!draft) return;

    const content = `
CERINA PROTOCOL - CBT EXERCISE
Generated: ${new Date().toLocaleString()}
Iterations: ${iteration}
Intent: ${intent}

═══════════════════════════════════════════════════════

${draft.title}

${Object.entries(draft.sections).map(([key, content]) => `
─────────────────────────────────────────────────────
${key.replace(/([A-Z])/g, ' $1').trim().toUpperCase()}
─────────────────────────────────────────────────────

${content}
`).join('\n')}

═══════════════════════════════════════════════════════

This protocol was generated by the Cerina Protocol Foundry,
a multi-agent CBT exercise generator with human oversight.

Total drafts created: ${previousDrafts.length}
Final iteration: ${iteration}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cerina-protocol-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!draft) {
    return (
      <div className="min-h-screen bg-gray-100 flex items-center justify-center">
        <p className="text-gray-500">No protocol available</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-emerald-50 p-6">
      <div className="max-w-4xl mx-auto">
        <div className="bg-white rounded-xl shadow-lg border border-gray-200 p-8 mb-6">
          <div className="flex items-center gap-4 mb-6">
            <div className="flex items-center justify-center w-12 h-12 bg-green-600 rounded-full">
              <CheckCircle className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Protocol Approved</h1>
              <p className="text-sm text-gray-600 mt-1">
                Completed after {iteration} iteration{iteration !== 1 ? 's' : ''}
              </p>
            </div>
          </div>

          <div className="bg-green-50 border border-green-200 rounded-lg p-4 mb-6">
            <p className="text-sm text-green-900">
              <span className="font-semibold">Original Intent:</span> {intent}
            </p>
          </div>

          <div className="space-y-4 mb-6">
            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">{draft.title}</h2>
            </div>

            {Object.entries(draft.sections).map(([key, content]) => (
              <div key={key} className="bg-gray-50 rounded-lg p-5 border border-gray-200">
                <h3 className="text-sm font-bold text-gray-700 uppercase tracking-wide mb-3 pb-2 border-b border-gray-300">
                  {key.replace(/([A-Z])/g, ' $1').trim()}
                </h3>
                <p className="text-sm text-gray-800 whitespace-pre-wrap leading-relaxed">
                  {content}
                </p>
              </div>
            ))}
          </div>

          <div className="flex gap-4">
            <button
              onClick={handleDownload}
              className="flex-1 flex items-center justify-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition-colors shadow-sm"
            >
              <Download className="w-5 h-5" />
              Download Protocol
            </button>

            <button
              onClick={onRestart}
              className="flex-1 flex items-center justify-center gap-2 px-6 py-3 bg-gray-600 hover:bg-gray-700 text-white font-semibold rounded-lg transition-colors shadow-sm"
            >
              <RotateCcw className="w-5 h-5" />
              Create New Protocol
            </button>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <h3 className="text-lg font-bold text-gray-900 mb-4">Generation Statistics</h3>
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-gray-50 rounded-lg p-4">
              <p className="text-sm text-gray-600">Total Iterations</p>
              <p className="text-2xl font-bold text-gray-900">{iteration}</p>
            </div>
            <div className="bg-gray-50 rounded-lg p-4">
              <p className="text-sm text-gray-600">Drafts Created</p>
              <p className="text-2xl font-bold text-gray-900">{previousDrafts.length}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
